version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=hera_bank
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      # - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:mysecret@postgres:5432/hera_bank?sslmode=disable
 
    depends_on:
      - postgres
    #   - redis
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
# volumes:
#   data-volume: